### ISSUE TITLE
If API is called too quickly, multiple UART commands can be sent before the first is responded to

### ISSUE THREAD

**Issue by johnnyman727** [tessel/camera-vc0706#3]
We should probably wrap UART calls in the the `sync-queue` module to avoid this.

**Comment by frankcash** [comment]
So if I'm understand this issue correctly and mode looks like [this](https://forums.tessel.io/t/camera-module-in-for-loop/1643), then if the camera fires on my broken "circuit" (myPin.rawRead === 1) then all these pictures are queued until the end of my infinite for loop?

**Comment by johnnyman727** [comment]
Yes - or more precisely, they are queued until you run out of memory. :)

**Comment by frankcash** [comment]
Thank you :+1:
