### ISSUE TITLE
`camera.resolutions` is undefined

### ISSUE THREAD

**Issue by Trott** [tessel/camera-vc0706#40]
This code logs `undefined` on the line that attempts to log `resolutions`.

````javascript


var tessel = require('tessel');
var camera = require('camera-vc0706').use(tessel.port['A']);


camera.on('ready', function() {
  console.log(typeof camera.resolutions);
  
});

camera.on('error', function(err) {
  console.error(err);
});
````

**Comment by johnnyman727** [comment]
The underlying issue here is that the `resolutions` property is actually a property of the library object returned by `require('camera-vc0706')` and not the camera object created with `use` as the documentation suggests.
