### ISSUE TITLE
Limited to a picture per second?

### ISSUE THREAD

**Issue by mrdoob** [tessel/camera-vc0706#45]
Seems like the camera takes one second to produce a picture.
Is this a hardware limitation?

**Comment by johnnyman727** [comment]
@mrdoob it's primarily a limitation of the Tessel 1 Runtime. The actual data transfer only takes a small fraction of a second but the logic around stopping frames, setting modes, calling callbacks, etc. adds quite a bit of overhead.

**Comment by mrdoob** [comment]
Oh, I see. Would the same module be able to stream with the Tessel 2?

**Comment by johnnyman727** [comment]
Unfortunately, no. The audio and camera modules are not compatible with T2. Instead, you can buy a webcam and have the ability to stream video (or just take stills if that's what you'd prefer).

**Comment by mrdoob** [comment]
Great! Thanks!
